# Generated by Django 4.2.2 on 2023-07-03 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('second_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('employment_type', models.CharField(choices=[('EMP', 'Employee'), ('MEM', 'Member')], default='MEM', max_length=3)),
                ('speciality', models.CharField(blank=True, max_length=50, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('url', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
                ('short_description', models.CharField(blank=True, max_length=50, null=True)),
                ('project_type', models.CharField(choices=[('INT', 'Internal'), ('EXT', 'External')], default='INT', max_length=3)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos')),
                ('contributors', models.ManyToManyField(related_name='projects', to='api.person')),
            ],
        ),
    ]
